#test_classroomproject.py

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestClassroomproject():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_classroomproject(self):
    self.driver.get("https://classroom.google.com/h")
    self.driver.set_window_size(785, 864)
    element = self.driver.find_element(By.CSS_SELECTOR, ".DShyMc-MzcwMTAyMDQ5MjU0 > .R4EiSb > .onkcGd")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.find_element(By.CSS_SELECTOR, ".DShyMc-MzY5MTE1MzY2MTUw .csjh4b").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".jrhqBd:nth-child(1) .Vlohie").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".r0VQac > .vwNuXe").click()
    self.driver.close()
